[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
addopts = -p pytest_homeassistant_custom_component
testpaths = tests
markers =
    enable_custom_integrations: enable custom integrations for Home Assistant tests
